title: Kuba Chrabański
logo: "/images/photo.png?raw=true"
description: >
  <h3>Python, Java, SQL, Linux</h3>
  <hr>
  I'm a student in <b>Computer Science</b> at the Faculty of Mathematics,
  Informatics and Mechanics, <b>University of Warsaw</b> (1st year) 
  <br><br>
  Currently expanding my knowledge in the field of AI,
  while working on a <a href="https://github.com/kakainet">Kakainet</a> group project ImageToLatex.
  <br><br><hr>
  <b>j.chrabanski@student.uw.edu.pl</b>
  <br><br>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0
